#!/bin/sh
#
# Title: Android Backup
# Author: Hypertekk
# Description: Backups Android Partitions for Galaxy Grand Prime (SM-S920L)
#
##########
# Main
	case "$1" in
		-l) 
			echo "aboot -> /dev/block/mmcblk0p5"
			echo "apnhlos -> /dev/block/mmcblk0p1"
			echo "backup -> /dev/block/mmcblk0p19"
			echo "boot -> /dev/block/mmcblk0p16"
			echo "cache -> /dev/block/mmcblk0p26"
			echo "ddr -> /dev/block/mmcblk0p4"
			echo "efs -> /dev/block/mmcblk0p13"
			echo "fota -> /dev/block/mmcblk0p18"
			echo "fsc -> /dev/block/mmcblk0p20"
			echo "fsg -> /dev/block/mmcblk0p9"
			echo "modem -> /dev/block/mmcblk0p2"
			echo "modemst1 -> /dev/block/mmcblk0p14"
			echo "modemst2 -> /dev/block/mmcblk0p15"
			echo "pad -> /dev/block/mmcblk0p11"
			echo "param -> /dev/block/mmcblk0p12"
			echo "persdata -> /dev/block/mmcblk0p24"
			echo "persist -> /dev/block/mmcblk0p22"
			echo "persistent -> /dev/block/mmcblk0p23"
			echo "qhee -> /dev/block/mmcblk0p8"
			echo "qsee -> /dev/block/mmcblk0p7"
			echo "recovery -> /dev/block/mmcblk0p17"
			echo "rpm -> /dev/block/mmcblk0p6"
			echo "sbl1 -> /dev/block/mmcblk0p3"
			echo "sec -> /dev/block/mmcblk0p10"
			echo "ssd -> /dev/block/mmcblk0p21"
			echo "system -> /dev/block/mmcblk0p25"
			echo "userdata -> /dev/block/mmcblk0p27"
		;;
		-a)
			dd if=/dev/block/mmcblk0 of=/storage/extSdCard/mmcblk0_Backup.img
		;;
		*) 	echo "Usage: backup_device [OPTION] "
			echo "   options:"
			echo "      -l  List partitions"
			echo "      -a  Backup all partitions"
			echo
		;;
	esac
