#!/bin/sh
#
# Name: Rsync File Transfer Script
# Description: Transfers file using Rsync
#
##########

USERREMOTE="devme"
HOSTNAME="192.168.0.30"
RECEIVELOCAL="/home/useradmin/Dev/Android/Receive"
SENDLOCAL="/home/useradmin/Dev/Android/Send"
RECEIVEREMOTE=""
SENDREMOTE=""

# Main
	case "$1" in
		s) 
			rsync -avh $USER@$HOSTNAME:$PHPFILESREMOTE/ $PHPFILESLOCAL
			rsync -avh $USER@$HOSTNAME:$WEBFILESREMOTE/ $WEBFILESLOCAL
		;;
		r)
			rsync -avh $PHPFILESLOCAL/ $USER@$HOSTNAME:$PHPFILESREMOTE
			rsync -avh $PHPFILESLOCAL/ $USER@$HOSTNAME:$WEBFILESREMOTE

		;;
	esac